# Site Config
title: Reddit Enhancement Suite
author: RES Team
description: Reddit Enhancement Suite (RES) is a suite of modules that enhances your Reddit browsing experience.
logo: res.png
transparent: transparent.png
google_analytics: UA-17650786-1
permalink: pretty
