# Site Config
title: Reddit Enhancement Suite
author: RES Team
description: Reddit Enhancement Suite (RES) is a suite of modules that enhances your Reddit browsing experience.
logo: res.png
transparent: transparent.png
google_analytics:
permalink: pretty
